global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['10.10.10.71:9090']
        labels:
          instance: prometheus

  - job_name: locust
    metrics_path: '/export/prometheus'
    static_configs:
      - targets: ['10.10.10.71:8089']
        labels:
          instance: locust

  - job_name: linux
    static_configs:
      - targets: ['10.10.10.71:9100']
        labels:
          instance: localhost
